
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 24 20:02:31 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKN_ASIGNACCION = 35;
  public static final int TKN_FUNCION = 2;
  public static final int TKN_LLAVEIZ = 14;
  public static final int TKN_DOSPUNTOS = 24;
  public static final int TKN_CHAR = 33;
  public static final int TKN_PARENTESISI = 12;
  public static final int TKN_PARENTESISD = 13;
  public static final int TKN_CASE = 26;
  public static final int TKN_IGUAL = 4;
  public static final int TKN_OR = 6;
  public static final int TKN_RETURN = 23;
  public static final int TKN_LETRA = 29;
  public static final int TKN_OPREL = 19;
  public static final int TKN_IF = 9;
  public static final int TKN_DIGITO = 8;
  public static final int TKN_ID = 36;
  public static final int TKN_SWITCH = 25;
  public static final int TKN_BOOLEAN = 34;
  public static final int TKN_MAIN = 5;
  public static final int TKN_COMILLA = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TKN_TRUE = 31;
  public static final int TKN_DIGITOFLOAT = 10;
  public static final int TKN_COMA = 3;
  public static final int TKN_VOID = 22;
  public static final int TKN_WHILE = 11;
  public static final int TKN_DEFAULT = 28;
  public static final int TKN_MULTI = 20;
  public static final int TKN_OPADICION = 18;
  public static final int TKN_INT = 32;
  public static final int TKN_FALSE = 30;
  public static final int TKN_IMPRIMIR = 7;
  public static final int TKN_FOR = 21;
  public static final int TKN_AND = 17;
  public static final int TKN_ENDCASE = 27;
  public static final int TKN_LLAVEDER = 15;
}

