
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 15 17:37:31 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKN_ASIGNACCION = 40;
  public static final int TKN_FUNCION = 4;
  public static final int TKN_LLAVEIZ = 15;
  public static final int TKN_DOSPUNTOS = 29;
  public static final int TKN_CHAR = 38;
  public static final int TKN_PARENTESISI = 13;
  public static final int TKN_PARENTESISD = 14;
  public static final int TKN_CASE = 31;
  public static final int TKN_IGUAL = 6;
  public static final int TKN_OR = 8;
  public static final int TKN_RETURN = 28;
  public static final int TKN_LETRA = 34;
  public static final int TKN_OPMULTI = 22;
  public static final int TKN_OPREL = 21;
  public static final int TKN_IF = 11;
  public static final int TKN_PUNTOCOMA = 2;
  public static final int TKN_DIGITO = 10;
  public static final int TKN_ID = 41;
  public static final int TKN_SWITCH = 30;
  public static final int TKN_BOOLEAN = 39;
  public static final int TKN_MAIN = 7;
  public static final int TKN_COMILLA = 18;
  public static final int EOF = 0;
  public static final int TKN_ERROR = 17;
  public static final int error = 1;
  public static final int TKN_TRUE = 36;
  public static final int TKN_DIGITOFLOAT = 12;
  public static final int TKN_COMA = 5;
  public static final int TKN_VOID = 27;
  public static final int TKN_WHILE = 26;
  public static final int TKN_OPADICION = 20;
  public static final int TKN_ELSE = 23;
  public static final int TKN_INT = 37;
  public static final int TKN_FALSE = 35;
  public static final int TKN_DEFINIR = 33;
  public static final int TKN_IMPRIMIR = 9;
  public static final int TKN_FOR = 25;
  public static final int TKN_COMPARACION = 3;
  public static final int TKN_THEN = 24;
  public static final int TKN_AND = 19;
  public static final int TKN_ENDCASE = 32;
  public static final int TKN_LLAVEDER = 16;
}

