
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 24 13:06:23 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKN_ASIGNACCION = 39;
  public static final int TKN_FUNCION = 3;
  public static final int TKN_LLAVEIZ = 15;
  public static final int TKN_DOSPUNTOS = 28;
  public static final int TKN_CHAR = 37;
  public static final int TKN_PARENTESISI = 13;
  public static final int TKN_PARENTESISD = 14;
  public static final int TKN_CASE = 30;
  public static final int TKN_IGUAL = 5;
  public static final int TKN_OR = 7;
  public static final int TKN_RETURN = 27;
  public static final int TKN_LETRA = 33;
  public static final int TKN_OPREL = 21;
  public static final int TKN_IF = 10;
  public static final int TKN_PUNTOCOMA = 2;
  public static final int TKN_DIGITO = 9;
  public static final int TKN_ID = 40;
  public static final int TKN_SWITCH = 29;
  public static final int TKN_BOOLEAN = 38;
  public static final int TKN_MAIN = 6;
  public static final int TKN_COMILLA = 18;
  public static final int EOF = 0;
  public static final int TKN_ERROR = 17;
  public static final int error = 1;
  public static final int TKN_TRUE = 35;
  public static final int TKN_DIGITOFLOAT = 11;
  public static final int TKN_COMA = 4;
  public static final int TKN_VOID = 26;
  public static final int TKN_WHILE = 12;
  public static final int TKN_DEFAULT = 32;
  public static final int TKN_MULTI = 22;
  public static final int TKN_OPADICION = 20;
  public static final int TKN_ELSE = 23;
  public static final int TKN_INT = 36;
  public static final int TKN_FALSE = 34;
  public static final int TKN_IMPRIMIR = 8;
  public static final int TKN_FOR = 25;
  public static final int TKN_THEN = 24;
  public static final int TKN_AND = 19;
  public static final int TKN_ENDCASE = 31;
  public static final int TKN_LLAVEDER = 16;
}

